/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransfersIndexRouteImport } from './routes/transfers.index'
import { Route as LandsIndexRouteImport } from './routes/lands.index'
import { Route as TransfersNewRouteImport } from './routes/transfers.new'
import { Route as TransfersTransferIdRouteImport } from './routes/transfers.$transferId'
import { Route as LandsNewRouteImport } from './routes/lands.new'
import { Route as LandsLandIdRouteImport } from './routes/lands.$landId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersIndexRoute = TransfersIndexRouteImport.update({
  id: '/transfers/',
  path: '/transfers/',
  getParentRoute: () => rootRouteImport,
} as any)
const LandsIndexRoute = LandsIndexRouteImport.update({
  id: '/lands/',
  path: '/lands/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersNewRoute = TransfersNewRouteImport.update({
  id: '/transfers/new',
  path: '/transfers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersTransferIdRoute = TransfersTransferIdRouteImport.update({
  id: '/transfers/$transferId',
  path: '/transfers/$transferId',
  getParentRoute: () => rootRouteImport,
} as any)
const LandsNewRoute = LandsNewRouteImport.update({
  id: '/lands/new',
  path: '/lands/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LandsLandIdRoute = LandsLandIdRouteImport.update({
  id: '/lands/$landId',
  path: '/lands/$landId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify': typeof VerifyRoute
  '/admin/users': typeof AdminUsersRoute
  '/lands/$landId': typeof LandsLandIdRoute
  '/lands/new': typeof LandsNewRoute
  '/transfers/$transferId': typeof TransfersTransferIdRoute
  '/transfers/new': typeof TransfersNewRoute
  '/lands/': typeof LandsIndexRoute
  '/transfers/': typeof TransfersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify': typeof VerifyRoute
  '/admin/users': typeof AdminUsersRoute
  '/lands/$landId': typeof LandsLandIdRoute
  '/lands/new': typeof LandsNewRoute
  '/transfers/$transferId': typeof TransfersTransferIdRoute
  '/transfers/new': typeof TransfersNewRoute
  '/lands': typeof LandsIndexRoute
  '/transfers': typeof TransfersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify': typeof VerifyRoute
  '/admin/users': typeof AdminUsersRoute
  '/lands/$landId': typeof LandsLandIdRoute
  '/lands/new': typeof LandsNewRoute
  '/transfers/$transferId': typeof TransfersTransferIdRoute
  '/transfers/new': typeof TransfersNewRoute
  '/lands/': typeof LandsIndexRoute
  '/transfers/': typeof TransfersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/verify'
    | '/admin/users'
    | '/lands/$landId'
    | '/lands/new'
    | '/transfers/$transferId'
    | '/transfers/new'
    | '/lands/'
    | '/transfers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/verify'
    | '/admin/users'
    | '/lands/$landId'
    | '/lands/new'
    | '/transfers/$transferId'
    | '/transfers/new'
    | '/lands'
    | '/transfers'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/verify'
    | '/admin/users'
    | '/lands/$landId'
    | '/lands/new'
    | '/transfers/$transferId'
    | '/transfers/new'
    | '/lands/'
    | '/transfers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  VerifyRoute: typeof VerifyRoute
  AdminUsersRoute: typeof AdminUsersRoute
  LandsLandIdRoute: typeof LandsLandIdRoute
  LandsNewRoute: typeof LandsNewRoute
  TransfersTransferIdRoute: typeof TransfersTransferIdRoute
  TransfersNewRoute: typeof TransfersNewRoute
  LandsIndexRoute: typeof LandsIndexRoute
  TransfersIndexRoute: typeof TransfersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers/': {
      id: '/transfers/'
      path: '/transfers'
      fullPath: '/transfers/'
      preLoaderRoute: typeof TransfersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lands/': {
      id: '/lands/'
      path: '/lands'
      fullPath: '/lands/'
      preLoaderRoute: typeof LandsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers/new': {
      id: '/transfers/new'
      path: '/transfers/new'
      fullPath: '/transfers/new'
      preLoaderRoute: typeof TransfersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers/$transferId': {
      id: '/transfers/$transferId'
      path: '/transfers/$transferId'
      fullPath: '/transfers/$transferId'
      preLoaderRoute: typeof TransfersTransferIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lands/new': {
      id: '/lands/new'
      path: '/lands/new'
      fullPath: '/lands/new'
      preLoaderRoute: typeof LandsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lands/$landId': {
      id: '/lands/$landId'
      path: '/lands/$landId'
      fullPath: '/lands/$landId'
      preLoaderRoute: typeof LandsLandIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  VerifyRoute: VerifyRoute,
  AdminUsersRoute: AdminUsersRoute,
  LandsLandIdRoute: LandsLandIdRoute,
  LandsNewRoute: LandsNewRoute,
  TransfersTransferIdRoute: TransfersTransferIdRoute,
  TransfersNewRoute: TransfersNewRoute,
  LandsIndexRoute: LandsIndexRoute,
  TransfersIndexRoute: TransfersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
